/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ApiVersionInfo model module.
 * @module model/ApiVersionInfo
 * @version v1
 */
export class ApiVersionInfo {
  /**
   * Constructs a new <code>ApiVersionInfo</code>.
   * @alias module:model/ApiVersionInfo
   * @class
   * @param name {String} Software name
   * @param version {String} Version number
   * @param manufacturer {String} Manufacturer
   */
  constructor(name, version, manufacturer) {
    this.name = name;
    this.version = version;
    this.manufacturer = manufacturer;
  }

  /**
   * Constructs a <code>ApiVersionInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApiVersionInfo} obj Optional instance to populate.
   * @return {module:model/ApiVersionInfo} The populated <code>ApiVersionInfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ApiVersionInfo();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('version'))
        obj.version = ApiClient.convertToType(data['version'], 'String');
      if (data.hasOwnProperty('manufacturer'))
        obj.manufacturer = ApiClient.convertToType(data['manufacturer'], 'String');
    }
    return obj;
  }
}

/**
 * Software name
 * @member {String} name
 */
ApiVersionInfo.prototype.name = undefined;

/**
 * Version number
 * @member {String} version
 */
ApiVersionInfo.prototype.version = undefined;

/**
 * Manufacturer
 * @member {String} manufacturer
 */
ApiVersionInfo.prototype.manufacturer = undefined;

