/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class BagCollectionStatusEnum.
 * @enum {String}
 * @readonly
 */
const BagCollectionStatusEnum = {
  /**
   * value: "none"
   * @const
   */
  none: "none",

  /**
   * value: "waitingDoorOpen"
   * @const
   */
  waitingDoorOpen: "waitingDoorOpen",

  /**
   * value: "changeBagsAndCloseDoor"
   * @const
   */
  changeBagsAndCloseDoor: "changeBagsAndCloseDoor",

  /**
   * value: "completed"
   * @const
   */
  completed: "completed",

  /**
   * value: "faulted"
   * @const
   */
  faulted: "faulted",

  /**
   * Returns a <code>BagCollectionStatusEnum</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/BagCollectionStatusEnum} The enum <code>BagCollectionStatusEnum</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {BagCollectionStatusEnum};