/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class BanknoteBagTypeEnum.
 * @enum {String}
 * @readonly
 */
const BanknoteBagTypeEnum = {
  /**
   * value: "none"
   * @const
   */
  none: "none",

  /**
   * value: "selfSealing"
   * @const
   */
  selfSealing: "selfSealing",

  /**
   * value: "canvas"
   * @const
   */
  canvas: "canvas",

  /**
   * value: "heatSealing"
   * @const
   */
  heatSealing: "heatSealing",

  /**
   * value: "stacking"
   * @const
   */
  stacking: "stacking",

  /**
   * value: "heatSealingV2"
   * @const
   */
  heatSealingV2: "heatSealingV2",

  /**
   * value: "smartCanvas"
   * @const
   */
  smartCanvas: "smartCanvas",

  /**
   * value: "unknown"
   * @const
   */
  unknown: "unknown",

  /**
   * Returns a <code>BanknoteBagTypeEnum</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/BanknoteBagTypeEnum} The enum <code>BanknoteBagTypeEnum</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {BanknoteBagTypeEnum};