/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {BanknoteBagTypeEnum} from './BanknoteBagTypeEnum';

/**
 * The BanknotesModuleInfo model module.
 * @module model/BanknotesModuleInfo
 * @version v1
 */
export class BanknotesModuleInfo {
  /**
   * Constructs a new <code>BanknotesModuleInfo</code>.
   * @alias module:model/BanknotesModuleInfo
   * @class
   * @param banknoteTemplate {Array.<String>} Banknotes module installed templates
   * @param firmware {String} Module firmware
   */
  constructor(banknoteTemplate, firmware) {
    this.banknoteTemplate = banknoteTemplate;
    this.firmware = firmware;
  }

  /**
   * Constructs a <code>BanknotesModuleInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BanknotesModuleInfo} obj Optional instance to populate.
   * @return {module:model/BanknotesModuleInfo} The populated <code>BanknotesModuleInfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BanknotesModuleInfo();
      if (data.hasOwnProperty('banknoteTemplate'))
        obj.banknoteTemplate = ApiClient.convertToType(data['banknoteTemplate'], ['String']);
      if (data.hasOwnProperty('model'))
        obj.model = ApiClient.convertToType(data['model'], 'String');
      if (data.hasOwnProperty('serialNumber'))
        obj.serialNumber = ApiClient.convertToType(data['serialNumber'], 'String');
      if (data.hasOwnProperty('firmware'))
        obj.firmware = ApiClient.convertToType(data['firmware'], 'String');
      if (data.hasOwnProperty('sensorFirmware'))
        obj.sensorFirmware = ApiClient.convertToType(data['sensorFirmware'], 'String');
      if (data.hasOwnProperty('bag'))
        obj.bag = BanknoteBagTypeEnum.constructFromObject(data['bag']);
    }
    return obj;
  }
}

/**
 * Banknotes module installed templates
 * @member {Array.<String>} banknoteTemplate
 */
BanknotesModuleInfo.prototype.banknoteTemplate = undefined;

/**
 * Module model
 * @member {String} model
 */
BanknotesModuleInfo.prototype.model = undefined;

/**
 * Module SerialNumber
 * @member {String} serialNumber
 */
BanknotesModuleInfo.prototype.serialNumber = undefined;

/**
 * Module firmware
 * @member {String} firmware
 */
BanknotesModuleInfo.prototype.firmware = undefined;

/**
 * Recognition Sensor firmware
 * @member {String} sensorFirmware
 */
BanknotesModuleInfo.prototype.sensorFirmware = undefined;

/**
 * @member {module:model/BanknoteBagTypeEnum} bag
 */
BanknotesModuleInfo.prototype.bag = undefined;

