/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Denomination} from './Denomination';

/**
 * The CashDetail model module.
 * @module model/CashDetail
 * @version v1
 */
export class CashDetail {
  /**
   * Constructs a new <code>CashDetail</code>.
   * @alias module:model/CashDetail
   * @class
   * @param denomination {module:model/Denomination} 
   * @param quantity {Number} Quantity
   */
  constructor(denomination, quantity) {
    this.denomination = denomination;
    this.quantity = quantity;
  }

  /**
   * Constructs a <code>CashDetail</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CashDetail} obj Optional instance to populate.
   * @return {module:model/CashDetail} The populated <code>CashDetail</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CashDetail();
      if (data.hasOwnProperty('denomination'))
        obj.denomination = Denomination.constructFromObject(data['denomination']);
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ApiClient.convertToType(data['quantity'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {module:model/Denomination} denomination
 */
CashDetail.prototype.denomination = undefined;

/**
 * Quantity
 * @member {Number} quantity
 */
CashDetail.prototype.quantity = undefined;

