/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Denomination} from './Denomination';

/**
 * The CashContent model module.
 * @module model/CashContent
 * @version v1
 */
export class CashContent {
  /**
   * Constructs a new <code>CashContent</code>.
   * @alias module:model/CashContent
   * @class
   * @param denomination {module:model/Denomination} 
   * @param quantity {Number} Quantity
   * @param stockIndex {Number} Stock index
   */
  constructor(denomination, quantity, stockIndex) {
    this.denomination = denomination;
    this.quantity = quantity;
    this.stockIndex = stockIndex;
  }

  /**
   * Constructs a <code>CashContent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CashContent} obj Optional instance to populate.
   * @return {module:model/CashContent} The populated <code>CashContent</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CashContent();
      if (data.hasOwnProperty('denomination'))
        obj.denomination = Denomination.constructFromObject(data['denomination']);
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ApiClient.convertToType(data['quantity'], 'Number');
      if (data.hasOwnProperty('stockIndex'))
        obj.stockIndex = ApiClient.convertToType(data['stockIndex'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {module:model/Denomination} denomination
 */
CashContent.prototype.denomination = undefined;

/**
 * Quantity
 * @member {Number} quantity
 */
CashContent.prototype.quantity = undefined;

/**
 * Stock index
 * @member {Number} stockIndex
 */
CashContent.prototype.stockIndex = undefined;

