/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CashContent} from './CashContent';
import {CassetteCollectionStatusEnum} from './CassetteCollectionStatusEnum';
import {ErrorCode} from './ErrorCode';
import {OperationStatusEnum} from './OperationStatusEnum';

/**
 * The CassetteCollectionOperationStatus model module.
 * @module model/CassetteCollectionOperationStatus
 * @version v1
 */
export class CassetteCollectionOperationStatus {
  /**
   * Constructs a new <code>CassetteCollectionOperationStatus</code>.
   * @alias module:model/CassetteCollectionOperationStatus
   * @class
   * @param cassetteCollectionStatus {module:model/CassetteCollectionStatusEnum} 
   * @param cassetteCollectionCashContentList {Array.<module:model/CashContent>} Content of the cassette removed
   * @param status {module:model/OperationStatusEnum} 
   * @param errorDescription {module:model/ErrorCode} 
   */
  constructor(cassetteCollectionStatus, cassetteCollectionCashContentList, status, errorDescription) {
    this.cassetteCollectionStatus = cassetteCollectionStatus;
    this.cassetteCollectionCashContentList = cassetteCollectionCashContentList;
    this.status = status;
    this.errorDescription = errorDescription;
  }

  /**
   * Constructs a <code>CassetteCollectionOperationStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CassetteCollectionOperationStatus} obj Optional instance to populate.
   * @return {module:model/CassetteCollectionOperationStatus} The populated <code>CassetteCollectionOperationStatus</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CassetteCollectionOperationStatus();
      if (data.hasOwnProperty('cassetteCollectionStatus'))
        obj.cassetteCollectionStatus = CassetteCollectionStatusEnum.constructFromObject(data['cassetteCollectionStatus']);
      if (data.hasOwnProperty('cassetteCollectionCashContentList'))
        obj.cassetteCollectionCashContentList = ApiClient.convertToType(data['cassetteCollectionCashContentList'], [CashContent]);
      if (data.hasOwnProperty('status'))
        obj.status = OperationStatusEnum.constructFromObject(data['status']);
      if (data.hasOwnProperty('errorDescription'))
        obj.errorDescription = ErrorCode.constructFromObject(data['errorDescription']);
    }
    return obj;
  }
}

/**
 * @member {module:model/CassetteCollectionStatusEnum} cassetteCollectionStatus
 */
CassetteCollectionOperationStatus.prototype.cassetteCollectionStatus = undefined;

/**
 * Content of the cassette removed
 * @member {Array.<module:model/CashContent>} cassetteCollectionCashContentList
 */
CassetteCollectionOperationStatus.prototype.cassetteCollectionCashContentList = undefined;

/**
 * @member {module:model/OperationStatusEnum} status
 */
CassetteCollectionOperationStatus.prototype.status = undefined;

/**
 * @member {module:model/ErrorCode} errorDescription
 */
CassetteCollectionOperationStatus.prototype.errorDescription = undefined;

