/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ErrorCode} from './ErrorCode';

/**
 * The CommandFailedResponse model module.
 * @module model/CommandFailedResponse
 * @version v1
 */
export class CommandFailedResponse {
  /**
   * Constructs a new <code>CommandFailedResponse</code>.
   * @alias module:model/CommandFailedResponse
   * @class
   * @param errorDescription {module:model/ErrorCode} 
   */
  constructor(errorDescription) {
    this.errorDescription = errorDescription;
  }

  /**
   * Constructs a <code>CommandFailedResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CommandFailedResponse} obj Optional instance to populate.
   * @return {module:model/CommandFailedResponse} The populated <code>CommandFailedResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CommandFailedResponse();
      if (data.hasOwnProperty('errorDescription'))
        obj.errorDescription = ErrorCode.constructFromObject(data['errorDescription']);
      if (data.hasOwnProperty('exception'))
        obj.exception = ApiClient.convertToType(data['exception'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/ErrorCode} errorDescription
 */
CommandFailedResponse.prototype.errorDescription = undefined;

/**
 * Exception
 * @member {String} exception
 */
CommandFailedResponse.prototype.exception = undefined;

