/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class CountingType.
 * @enum {String}
 * @readonly
 */
const CountingType = {
  /**
   * value: "content"
   * @const
   */
  content: "content",

  /**
   * value: "available"
   * @const
   */
  available: "available",

  /**
   * value: "unfit"
   * @const
   */
  unfit: "unfit",

  /**
   * value: "counterfeit"
   * @const
   */
  counterfeit: "counterfeit",

  /**
   * value: "suspect"
   * @const
   */
  suspect: "suspect",

  /**
   * Returns a <code>CountingType</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/CountingType} The enum <code>CountingType</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {CountingType};