/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CurrencyAmount model module.
 * @module model/CurrencyAmount
 * @version v1
 */
export class CurrencyAmount {
  /**
   * Constructs a new <code>CurrencyAmount</code>.
   * @alias module:model/CurrencyAmount
   * @class
   * @param currency {String} Currency
   * @param amount {Number} Amount
   */
  constructor(currency, amount) {
    this.currency = currency;
    this.amount = amount;
  }

  /**
   * Constructs a <code>CurrencyAmount</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CurrencyAmount} obj Optional instance to populate.
   * @return {module:model/CurrencyAmount} The populated <code>CurrencyAmount</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CurrencyAmount();
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], 'String');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
    }
    return obj;
  }
}

/**
 * Currency
 * @member {String} currency
 */
CurrencyAmount.prototype.currency = undefined;

/**
 * Amount
 * @member {Number} amount
 */
CurrencyAmount.prototype.amount = undefined;

