/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CashMediaType} from './CashMediaType';

/**
 * The DenominationConfig model module.
 * @module model/DenominationConfig
 * @version v1
 */
export class DenominationConfig {
  /**
   * Constructs a new <code>DenominationConfig</code>.
   * @alias module:model/DenominationConfig
   * @class
   * @param revision {String} Denomination revision
   * @param currency {String} Currency in ISO 4217 format
   * @param value {Number} Value
   * @param cashType {module:model/CashMediaType} 
   */
  constructor(revision, currency, value, cashType) {
    this.revision = revision;
    this.currency = currency;
    this.value = value;
    this.cashType = cashType;
  }

  /**
   * Constructs a <code>DenominationConfig</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DenominationConfig} obj Optional instance to populate.
   * @return {module:model/DenominationConfig} The populated <code>DenominationConfig</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DenominationConfig();
      if (data.hasOwnProperty('revision'))
        obj.revision = ApiClient.convertToType(data['revision'], 'String');
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'Number');
      if (data.hasOwnProperty('cashType'))
        obj.cashType = CashMediaType.constructFromObject(data['cashType']);
    }
    return obj;
  }
}

/**
 * Denomination revision
 * @member {String} revision
 */
DenominationConfig.prototype.revision = undefined;

/**
 * Currency in ISO 4217 format
 * @member {String} currency
 */
DenominationConfig.prototype.currency = undefined;

/**
 * Value
 * @member {Number} value
 */
DenominationConfig.prototype.value = undefined;

/**
 * @member {module:model/CashMediaType} cashType
 */
DenominationConfig.prototype.cashType = undefined;

