/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class DeviceGlobalStatusEnum.
 * @enum {String}
 * @readonly
 */
const DeviceGlobalStatusEnum = {
  /**
   * value: "ok"
   * @const
   */
  ok: "ok",

  /**
   * value: "ko"
   * @const
   */
  ko: "ko",

  /**
   * value: "partiallyWorking"
   * @const
   */
  partiallyWorking: "partiallyWorking",

  /**
   * value: "busy"
   * @const
   */
  busy: "busy",

  /**
   * value: "offline"
   * @const
   */
  offline: "offline",

  /**
   * value: "warning"
   * @const
   */
  warning: "warning",

  /**
   * value: "warningCIT"
   * @const
   */
  warningCIT: "warningCIT",

  /**
   * value: "technicalInterventionRequired"
   * @const
   */
  technicalInterventionRequired: "technicalInterventionRequired",

  /**
   * value: "notConfigured"
   * @const
   */
  notConfigured: "notConfigured",

  /**
   * Returns a <code>DeviceGlobalStatusEnum</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/DeviceGlobalStatusEnum} The enum <code>DeviceGlobalStatusEnum</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {DeviceGlobalStatusEnum};