/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {BanknotesModuleInfo} from './BanknotesModuleInfo';
import {CoinsModuleInfo} from './CoinsModuleInfo';
import {DoorConfigurationEnum} from './DoorConfigurationEnum';

/**
 * The DeviceInfo model module.
 * @module model/DeviceInfo
 * @version v1
 */
export class DeviceInfo {
  /**
   * Constructs a new <code>DeviceInfo</code>.
   * @alias module:model/DeviceInfo
   * @class
   * @param model {String} Device model
   * @param serialNumber {String} Device serial number
   */
  constructor(model, serialNumber) {
    this.model = model;
    this.serialNumber = serialNumber;
  }

  /**
   * Constructs a <code>DeviceInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeviceInfo} obj Optional instance to populate.
   * @return {module:model/DeviceInfo} The populated <code>DeviceInfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeviceInfo();
      if (data.hasOwnProperty('model'))
        obj.model = ApiClient.convertToType(data['model'], 'String');
      if (data.hasOwnProperty('serialNumber'))
        obj.serialNumber = ApiClient.convertToType(data['serialNumber'], 'String');
      if (data.hasOwnProperty('banknotesModule'))
        obj.banknotesModule = BanknotesModuleInfo.constructFromObject(data['banknotesModule']);
      if (data.hasOwnProperty('coinsModule'))
        obj.coinsModule = CoinsModuleInfo.constructFromObject(data['coinsModule']);
      if (data.hasOwnProperty('safeDoor'))
        obj.safeDoor = DoorConfigurationEnum.constructFromObject(data['safeDoor']);
    }
    return obj;
  }
}

/**
 * Device model
 * @member {String} model
 */
DeviceInfo.prototype.model = undefined;

/**
 * Device serial number
 * @member {String} serialNumber
 */
DeviceInfo.prototype.serialNumber = undefined;

/**
 * @member {module:model/BanknotesModuleInfo} banknotesModule
 */
DeviceInfo.prototype.banknotesModule = undefined;

/**
 * @member {module:model/CoinsModuleInfo} coinsModule
 */
DeviceInfo.prototype.coinsModule = undefined;

/**
 * @member {module:model/DoorConfigurationEnum} safeDoor
 */
DeviceInfo.prototype.safeDoor = undefined;

