/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ApiVersionInfo} from './ApiVersionInfo';
import {DeviceInfo} from './DeviceInfo';

/**
 * The DeviceInfoResponse model module.
 * @module model/DeviceInfoResponse
 * @version v1
 */
export class DeviceInfoResponse {
  /**
   * Constructs a new <code>DeviceInfoResponse</code>.
   * @alias module:model/DeviceInfoResponse
   * @class
   * @param api {module:model/ApiVersionInfo} 
   * @param device {module:model/DeviceInfo} 
   */
  constructor(api, device) {
    this.api = api;
    this.device = device;
  }

  /**
   * Constructs a <code>DeviceInfoResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeviceInfoResponse} obj Optional instance to populate.
   * @return {module:model/DeviceInfoResponse} The populated <code>DeviceInfoResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeviceInfoResponse();
      if (data.hasOwnProperty('api'))
        obj.api = ApiVersionInfo.constructFromObject(data['api']);
      if (data.hasOwnProperty('device'))
        obj.device = DeviceInfo.constructFromObject(data['device']);
    }
    return obj;
  }
}

/**
 * @member {module:model/ApiVersionInfo} api
 */
DeviceInfoResponse.prototype.api = undefined;

/**
 * @member {module:model/DeviceInfo} device
 */
DeviceInfoResponse.prototype.device = undefined;

