/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {DeviceContentDetail} from './DeviceContentDetail';

/**
 * The DeviceContentResponse model module.
 * @module model/DeviceContentResponse
 * @version v1
 */
export class DeviceContentResponse {
  /**
   * Constructs a new <code>DeviceContentResponse</code>.
   * @alias module:model/DeviceContentResponse
   * @class
   * @param deviceContent {Array.<module:model/DeviceContentDetail>} Device Content
   * @param isPartial {Boolean} Flag to notify if the content is partial because one module is offline
   */
  constructor(deviceContent, isPartial) {
    this.deviceContent = deviceContent;
    this.isPartial = isPartial;
  }

  /**
   * Constructs a <code>DeviceContentResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeviceContentResponse} obj Optional instance to populate.
   * @return {module:model/DeviceContentResponse} The populated <code>DeviceContentResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeviceContentResponse();
      if (data.hasOwnProperty('deviceContent'))
        obj.deviceContent = ApiClient.convertToType(data['deviceContent'], [DeviceContentDetail]);
      if (data.hasOwnProperty('isPartial'))
        obj.isPartial = ApiClient.convertToType(data['isPartial'], 'Boolean');
    }
    return obj;
  }
}

/**
 * Device Content
 * @member {Array.<module:model/DeviceContentDetail>} deviceContent
 */
DeviceContentResponse.prototype.deviceContent = undefined;

/**
 * Flag to notify if the content is partial because one module is offline
 * @member {Boolean} isPartial
 */
DeviceContentResponse.prototype.isPartial = undefined;

