/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CashCount} from './CashCount';
import {CountingType} from './CountingType';

/**
 * The DeviceCountingDetail model module.
 * @module model/DeviceCountingDetail
 * @version v1
 */
export class DeviceCountingDetail {
  /**
   * Constructs a new <code>DeviceCountingDetail</code>.
   * @alias module:model/DeviceCountingDetail
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DeviceCountingDetail</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeviceCountingDetail} obj Optional instance to populate.
   * @return {module:model/DeviceCountingDetail} The populated <code>DeviceCountingDetail</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeviceCountingDetail();
      if (data.hasOwnProperty('type'))
        obj.type = CountingType.constructFromObject(data['type']);
      if (data.hasOwnProperty('counting'))
        obj.counting = ApiClient.convertToType(data['counting'], [CashCount]);
    }
    return obj;
  }
}

/**
 * @member {module:model/CountingType} type
 */
DeviceCountingDetail.prototype.type = undefined;

/**
 * Counting detailed of the counting type
 * @member {Array.<module:model/CashCount>} counting
 */
DeviceCountingDetail.prototype.counting = undefined;

