/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CashCount} from './CashCount';

/**
 * The DeviceContentDetail model module.
 * @module model/DeviceContentDetail
 * @version v1
 */
export class DeviceContentDetail {
  /**
   * Constructs a new <code>DeviceContentDetail</code>.
   * @alias module:model/DeviceContentDetail
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DeviceContentDetail</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeviceContentDetail} obj Optional instance to populate.
   * @return {module:model/DeviceContentDetail} The populated <code>DeviceContentDetail</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeviceContentDetail();
      if (data.hasOwnProperty('content'))
        obj.content = ApiClient.convertToType(data['content'], [CashCount]);
      if (data.hasOwnProperty('stockIndex'))
        obj.stockIndex = ApiClient.convertToType(data['stockIndex'], 'Number');
    }
    return obj;
  }
}

/**
 * Stock Content
 * @member {Array.<module:model/CashCount>} content
 */
DeviceContentDetail.prototype.content = undefined;

/**
 * Stock index
 * @member {Number} stockIndex
 */
DeviceContentDetail.prototype.stockIndex = undefined;

