/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {DoorTypeEnum} from './DoorTypeEnum';

/**
 * The DoorStatus model module.
 * @module model/DoorStatus
 * @version v1
 */
export class DoorStatus {
  /**
   * Constructs a new <code>DoorStatus</code>.
   * @alias module:model/DoorStatus
   * @class
   * @param doorType {module:model/DoorTypeEnum} 
   * @param opened {Boolean} Is the safe opened? (True if ShutterOpened or ShaftOpened are true)
   * @param shutterOpened {Boolean} Is the Shutter opened? True if the door is not in the rest position.
   * @param shaftOpened {Boolean} Is the Shaft opened? True if the handle of the door isn't rotated in closed position.
   */
  constructor(doorType, opened, shutterOpened, shaftOpened) {
    this.doorType = doorType;
    this.opened = opened;
    this.shutterOpened = shutterOpened;
    this.shaftOpened = shaftOpened;
  }

  /**
   * Constructs a <code>DoorStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DoorStatus} obj Optional instance to populate.
   * @return {module:model/DoorStatus} The populated <code>DoorStatus</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DoorStatus();
      if (data.hasOwnProperty('doorType'))
        obj.doorType = DoorTypeEnum.constructFromObject(data['doorType']);
      if (data.hasOwnProperty('opened'))
        obj.opened = ApiClient.convertToType(data['opened'], 'Boolean');
      if (data.hasOwnProperty('shutterOpened'))
        obj.shutterOpened = ApiClient.convertToType(data['shutterOpened'], 'Boolean');
      if (data.hasOwnProperty('shaftOpened'))
        obj.shaftOpened = ApiClient.convertToType(data['shaftOpened'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {module:model/DoorTypeEnum} doorType
 */
DoorStatus.prototype.doorType = undefined;

/**
 * Is the safe opened? (True if ShutterOpened or ShaftOpened are true)
 * @member {Boolean} opened
 */
DoorStatus.prototype.opened = undefined;

/**
 * Is the Shutter opened? True if the door is not in the rest position.
 * @member {Boolean} shutterOpened
 */
DoorStatus.prototype.shutterOpened = undefined;

/**
 * Is the Shaft opened? True if the handle of the door isn't rotated in closed position.
 * @member {Boolean} shaftOpened
 */
DoorStatus.prototype.shaftOpened = undefined;

