/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class DoorTypeEnum.
 * @enum {String}
 * @readonly
 */
const DoorTypeEnum = {
  /**
   * value: "unique"
   * @const
   */
  unique: "unique",

  /**
   * value: "banknotesModule"
   * @const
   */
  banknotesModule: "banknotesModule",

  /**
   * value: "coinsModule"
   * @const
   */
  coinsModule: "coinsModule",

  /**
   * Returns a <code>DoorTypeEnum</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/DoorTypeEnum} The enum <code>DoorTypeEnum</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {DoorTypeEnum};