/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class DoorConfigurationEnum.
 * @enum {String}
 * @readonly
 */
const DoorConfigurationEnum = {
  /**
   * value: "none"
   * @const
   */
  none: "none",

  /**
   * value: "onePerModule"
   * @const
   */
  onePerModule: "onePerModule",

  /**
   * value: "unique"
   * @const
   */
  unique: "unique",

  /**
   * Returns a <code>DoorConfigurationEnum</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/DoorConfigurationEnum} The enum <code>DoorConfigurationEnum</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {DoorConfigurationEnum};