/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class ErrorCode.
 * @enum {String}
 * @readonly
 */
const ErrorCode = {
  /**
   * value: "genericError"
   * @const
   */
  genericError: "genericError",

  /**
   * value: "noError"
   * @const
   */
  noError: "noError",

  /**
   * value: "busy"
   * @const
   */
  busy: "busy",

  /**
   * value: "userMandatory"
   * @const
   */
  userMandatory: "userMandatory",

  /**
   * value: "commandFailed"
   * @const
   */
  commandFailed: "commandFailed",

  /**
   * value: "machineNotReady"
   * @const
   */
  machineNotReady: "machineNotReady",

  /**
   * value: "requestedDispensationNotAvailable"
   * @const
   */
  requestedDispensationNotAvailable: "requestedDispensationNotAvailable",

  /**
   * value: "minimumKitDisabled"
   * @const
   */
  minimumKitDisabled: "minimumKitDisabled",

  /**
   * value: "minimumKitNotConfigured"
   * @const
   */
  minimumKitNotConfigured: "minimumKitNotConfigured",

  /**
   * value: "exception"
   * @const
   */
  exception: "exception",

  /**
   * value: "onlyServiceAllowed"
   * @const
   */
  onlyServiceAllowed: "onlyServiceAllowed",

  /**
   * value: "loginFailed"
   * @const
   */
  loginFailed: "loginFailed",

  /**
   * value: "outputTrayOccupied"
   * @const
   */
  outputTrayOccupied: "outputTrayOccupied",

  /**
   * value: "dispensedMoreThanRequested"
   * @const
   */
  dispensedMoreThanRequested: "dispensedMoreThanRequested",

  /**
   * value: "notFound"
   * @const
   */
  notFound: "notFound",

  /**
   * Returns a <code>ErrorCode</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/ErrorCode} The enum <code>ErrorCode</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {ErrorCode};