/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ExchangeRate model module.
 * @module model/ExchangeRate
 * @version v1
 */
export class ExchangeRate {
  /**
   * Constructs a new <code>ExchangeRate</code>.
   * @alias module:model/ExchangeRate
   * @class
   * @param currency {String} Currency
   * @param ratio {Number} Ratio between primary and secondary currencies.  Example using main currency EUR and secondary currency USD: [ {\"currency\": \"USD\", \"ratio\":1.25 } ] will result in 1 USD = 1.25 EUR
   */
  constructor(currency, ratio) {
    this.currency = currency;
    this.ratio = ratio;
  }

  /**
   * Constructs a <code>ExchangeRate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExchangeRate} obj Optional instance to populate.
   * @return {module:model/ExchangeRate} The populated <code>ExchangeRate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ExchangeRate();
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], 'String');
      if (data.hasOwnProperty('ratio'))
        obj.ratio = ApiClient.convertToType(data['ratio'], 'Number');
    }
    return obj;
  }
}

/**
 * Currency
 * @member {String} currency
 */
ExchangeRate.prototype.currency = undefined;

/**
 * Ratio between primary and secondary currencies.  Example using main currency EUR and secondary currency USD: [ {\"currency\": \"USD\", \"ratio\":1.25 } ] will result in 1 USD = 1.25 EUR
 * @member {Number} ratio
 */
ExchangeRate.prototype.ratio = undefined;

