/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ErrorCode} from './ErrorCode';
import {ManualRefillStatusEnum} from './ManualRefillStatusEnum';
import {OperationStatusEnum} from './OperationStatusEnum';

/**
 * The ManualRefillOperationStatus model module.
 * @module model/ManualRefillOperationStatus
 * @version v1
 */
export class ManualRefillOperationStatus {
  /**
   * Constructs a new <code>ManualRefillOperationStatus</code>.
   * @alias module:model/ManualRefillOperationStatus
   * @class
   * @param status {module:model/OperationStatusEnum} 
   * @param errorDescription {module:model/ErrorCode} 
   */
  constructor(status, errorDescription) {
    this.status = status;
    this.errorDescription = errorDescription;
  }

  /**
   * Constructs a <code>ManualRefillOperationStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ManualRefillOperationStatus} obj Optional instance to populate.
   * @return {module:model/ManualRefillOperationStatus} The populated <code>ManualRefillOperationStatus</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ManualRefillOperationStatus();
      if (data.hasOwnProperty('manualRefillStatus'))
        obj.manualRefillStatus = ManualRefillStatusEnum.constructFromObject(data['manualRefillStatus']);
      if (data.hasOwnProperty('status'))
        obj.status = OperationStatusEnum.constructFromObject(data['status']);
      if (data.hasOwnProperty('errorDescription'))
        obj.errorDescription = ErrorCode.constructFromObject(data['errorDescription']);
    }
    return obj;
  }
}

/**
 * @member {module:model/ManualRefillStatusEnum} manualRefillStatus
 */
ManualRefillOperationStatus.prototype.manualRefillStatus = undefined;

/**
 * @member {module:model/OperationStatusEnum} status
 */
ManualRefillOperationStatus.prototype.status = undefined;

/**
 * @member {module:model/ErrorCode} errorDescription
 */
ManualRefillOperationStatus.prototype.errorDescription = undefined;

