/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class ManualRefillStatusEnum.
 * @enum {String}
 * @readonly
 */
const ManualRefillStatusEnum = {
  /**
   * value: "waitRefillDoorOpen"
   * @const
   */
  waitRefillDoorOpen: "waitRefillDoorOpen",

  /**
   * value: "waitRefillDoorClose"
   * @const
   */
  waitRefillDoorClose: "waitRefillDoorClose",

  /**
   * value: "waitNewContent"
   * @const
   */
  waitNewContent: "waitNewContent",

  /**
   * value: "writingNewContent"
   * @const
   */
  writingNewContent: "writingNewContent",

  /**
   * value: "completed"
   * @const
   */
  completed: "completed",

  /**
   * value: "faulted"
   * @const
   */
  faulted: "faulted",

  /**
   * Returns a <code>ManualRefillStatusEnum</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/ManualRefillStatusEnum} The enum <code>ManualRefillStatusEnum</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {ManualRefillStatusEnum};