/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CashDetail} from './CashDetail';

/**
 * The MinimumKitConfiguration model module.
 * @module model/MinimumKitConfiguration
 * @version v1
 */
export class MinimumKitConfiguration {
  /**
   * Constructs a new <code>MinimumKitConfiguration</code>.
   * @alias module:model/MinimumKitConfiguration
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MinimumKitConfiguration</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MinimumKitConfiguration} obj Optional instance to populate.
   * @return {module:model/MinimumKitConfiguration} The populated <code>MinimumKitConfiguration</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MinimumKitConfiguration();
      if (data.hasOwnProperty('enabled'))
        obj.enabled = ApiClient.convertToType(data['enabled'], 'Boolean');
      if (data.hasOwnProperty('cashDetailList'))
        obj.cashDetailList = ApiClient.convertToType(data['cashDetailList'], [CashDetail]);
    }
    return obj;
  }
}

/**
 * Boolean to enable or disable the minimum kit
 * @member {Boolean} enabled
 */
MinimumKitConfiguration.prototype.enabled = undefined;

/**
 * Minimum kit configuration details
 * @member {Array.<module:model/CashDetail>} cashDetailList
 */
MinimumKitConfiguration.prototype.cashDetailList = undefined;

