/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class OperationAvailabilityEnum.
 * @enum {String}
 * @readonly
 */
const OperationAvailabilityEnum = {
  /**
   * value: "notExecutable"
   * @const
   */
  notExecutable: "notExecutable",

  /**
   * value: "executable"
   * @const
   */
  executable: "executable",

  /**
   * Returns a <code>OperationAvailabilityEnum</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/OperationAvailabilityEnum} The enum <code>OperationAvailabilityEnum</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {OperationAvailabilityEnum};