/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class OperationStatusEnum.
 * @enum {String}
 * @readonly
 */
const OperationStatusEnum = {
  /**
   * value: "unknown"
   * @const
   */
  unknown: "unknown",

  /**
   * value: "idle"
   * @const
   */
  idle: "idle",

  /**
   * value: "starting"
   * @const
   */
  starting: "starting",

  /**
   * value: "running"
   * @const
   */
  running: "running",

  /**
   * value: "faulted"
   * @const
   */
  faulted: "faulted",

  /**
   * value: "completed"
   * @const
   */
  completed: "completed",

  /**
   * Returns a <code>OperationStatusEnum</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/OperationStatusEnum} The enum <code>OperationStatusEnum</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {OperationStatusEnum};