/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class PaymentStatusEnum.
 * @enum {String}
 * @readonly
 */
const PaymentStatusEnum = {
  /**
   * value: "depositRunning"
   * @const
   */
  depositRunning: "depositRunning",

  /**
   * value: "depositJammed"
   * @const
   */
  depositJammed: "depositJammed",

  /**
   * value: "depositDone"
   * @const
   */
  depositDone: "depositDone",

  /**
   * value: "depositNotesIn"
   * @const
   */
  depositNotesIn: "depositNotesIn",

  /**
   * value: "depositRemoveNotesOut"
   * @const
   */
  depositRemoveNotesOut: "depositRemoveNotesOut",

  /**
   * value: "dispenseRunning"
   * @const
   */
  dispenseRunning: "dispenseRunning",

  /**
   * value: "dispenseJammed"
   * @const
   */
  dispenseJammed: "dispenseJammed",

  /**
   * value: "dispenseDone"
   * @const
   */
  dispenseDone: "dispenseDone",

  /**
   * value: "removeTranche"
   * @const
   */
  removeTranche: "removeTranche",

  /**
   * value: "notAvailable"
   * @const
   */
  notAvailable: "notAvailable",

  /**
   * value: "faulted"
   * @const
   */
  faulted: "faulted",

  /**
   * value: "unknown"
   * @const
   */
  unknown: "unknown",

  /**
   * Returns a <code>PaymentStatusEnum</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/PaymentStatusEnum} The enum <code>PaymentStatusEnum</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {PaymentStatusEnum};