/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The StartEmptyOutReqData model module.
 * @module model/StartEmptyOutReqData
 * @version v1
 */
export class StartEmptyOutReqData {
  /**
   * Constructs a new <code>StartEmptyOutReqData</code>.
   * @alias module:model/StartEmptyOutReqData
   * @class
   * @param selectedStocksToEmpty {Array.<Number>} Stock index array
   */
  constructor(selectedStocksToEmpty) {
    this.selectedStocksToEmpty = selectedStocksToEmpty;
  }

  /**
   * Constructs a <code>StartEmptyOutReqData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StartEmptyOutReqData} obj Optional instance to populate.
   * @return {module:model/StartEmptyOutReqData} The populated <code>StartEmptyOutReqData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new StartEmptyOutReqData();
      if (data.hasOwnProperty('selectedStocksToEmpty'))
        obj.selectedStocksToEmpty = ApiClient.convertToType(data['selectedStocksToEmpty'], ['Number']);
    }
    return obj;
  }
}

/**
 * Stock index array
 * @member {Array.<Number>} selectedStocksToEmpty
 */
StartEmptyOutReqData.prototype.selectedStocksToEmpty = undefined;

