/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class StockStatusEnum.
 * @enum {String}
 * @readonly
 */
const StockStatusEnum = {
  /**
   * value: "disabled"
   * @const
   */
  disabled: "disabled",

  /**
   * value: "ok"
   * @const
   */
  ok: "ok",

  /**
   * value: "nearEmpty"
   * @const
   */
  nearEmpty: "nearEmpty",

  /**
   * value: "empty"
   * @const
   */
  empty: "empty",

  /**
   * value: "nearFull"
   * @const
   */
  nearFull: "nearFull",

  /**
   * value: "full"
   * @const
   */
  full: "full",

  /**
   * value: "possibleMiscount"
   * @const
   */
  possibleMiscount: "possibleMiscount",

  /**
   * value: "blocked"
   * @const
   */
  blocked: "blocked",

  /**
   * value: "unlocked"
   * @const
   */
  unlocked: "unlocked",

  /**
   * value: "removed"
   * @const
   */
  removed: "removed",

  /**
   * Returns a <code>StockStatusEnum</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/StockStatusEnum} The enum <code>StockStatusEnum</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {StockStatusEnum};