/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class StockTypeEnum.
 * @enum {String}
 * @readonly
 */
const StockTypeEnum = {
  /**
   * value: "drum"
   * @const
   */
  drum: "drum",

  /**
   * value: "bag"
   * @const
   */
  bag: "bag",

  /**
   * value: "hopper"
   * @const
   */
  hopper: "hopper",

  /**
   * value: "cassette"
   * @const
   */
  cassette: "cassette",

  /**
   * value: "unknown"
   * @const
   */
  unknown: "unknown",

  /**
   * Returns a <code>StockTypeEnum</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/StockTypeEnum} The enum <code>StockTypeEnum</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {StockTypeEnum};