/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TransactionTotals model module.
 * @module model/TransactionTotals
 * @version v1
 */
export class TransactionTotals {
  /**
   * Constructs a new <code>TransactionTotals</code>.
   * @alias module:model/TransactionTotals
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TransactionTotals</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TransactionTotals} obj Optional instance to populate.
   * @return {module:model/TransactionTotals} The populated <code>TransactionTotals</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TransactionTotals();
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], 'String');
      if (data.hasOwnProperty('deposited'))
        obj.deposited = ApiClient.convertToType(data['deposited'], 'Number');
      if (data.hasOwnProperty('dispensed'))
        obj.dispensed = ApiClient.convertToType(data['dispensed'], 'Number');
      if (data.hasOwnProperty('transfered'))
        obj.transfered = ApiClient.convertToType(data['transfered'], 'Number');
    }
    return obj;
  }
}

/**
 * Currency
 * @member {String} currency
 */
TransactionTotals.prototype.currency = undefined;

/**
 * Amount of what has been deposited during the transaction
 * @member {Number} deposited
 */
TransactionTotals.prototype.deposited = undefined;

/**
 * Amount of what has been deposited during the transaction
 * @member {Number} dispensed
 */
TransactionTotals.prototype.dispensed = undefined;

/**
 * Amount of what has been tranfered during the transaction
 * @member {Number} transfered
 */
TransactionTotals.prototype.transfered = undefined;

