/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {TransactionCountings} from './TransactionCountings';
import {TransactionTotals} from './TransactionTotals';
import {TransactionTypeEnum} from './TransactionTypeEnum';

/**
 * The TransactionResponse model module.
 * @module model/TransactionResponse
 * @version v1
 */
export class TransactionResponse {
  /**
   * Constructs a new <code>TransactionResponse</code>.
   * @alias module:model/TransactionResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TransactionResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TransactionResponse} obj Optional instance to populate.
   * @return {module:model/TransactionResponse} The populated <code>TransactionResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TransactionResponse();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('timestamp'))
        obj.timestamp = ApiClient.convertToType(data['timestamp'], 'Date');
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = TransactionTypeEnum.constructFromObject(data['type']);
      if (data.hasOwnProperty('countings'))
        obj.countings = TransactionCountings.constructFromObject(data['countings']);
      if (data.hasOwnProperty('totals'))
        obj.totals = ApiClient.convertToType(data['totals'], [TransactionTotals]);
      if (data.hasOwnProperty('transactionReference'))
        obj.transactionReference = ApiClient.convertToType(data['transactionReference'], 'String');
    }
    return obj;
  }
}

/**
 * Transaction ID
 * @member {Number} id
 */
TransactionResponse.prototype.id = undefined;

/**
 * Transaction end timestamp
 * @member {Date} timestamp
 */
TransactionResponse.prototype.timestamp = undefined;

/**
 * Username who has executed the transaction
 * @member {String} username
 */
TransactionResponse.prototype.username = undefined;

/**
 * @member {module:model/TransactionTypeEnum} type
 */
TransactionResponse.prototype.type = undefined;

/**
 * @member {module:model/TransactionCountings} countings
 */
TransactionResponse.prototype.countings = undefined;

/**
 * Totals of what has been moved during the operation
 * @member {Array.<module:model/TransactionTotals>} totals
 */
TransactionResponse.prototype.totals = undefined;

/**
 * Transaction reference
 * @member {String} transactionReference
 */
TransactionResponse.prototype.transactionReference = undefined;

