/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CashCount} from './CashCount';

/**
 * The TransactionCountings model module.
 * @module model/TransactionCountings
 * @version v1
 */
export class TransactionCountings {
  /**
   * Constructs a new <code>TransactionCountings</code>.
   * @alias module:model/TransactionCountings
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TransactionCountings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TransactionCountings} obj Optional instance to populate.
   * @return {module:model/TransactionCountings} The populated <code>TransactionCountings</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TransactionCountings();
      if (data.hasOwnProperty('deposited'))
        obj.deposited = ApiClient.convertToType(data['deposited'], [CashCount]);
      if (data.hasOwnProperty('dispensed'))
        obj.dispensed = ApiClient.convertToType(data['dispensed'], [CashCount]);
      if (data.hasOwnProperty('transfered'))
        obj.transfered = ApiClient.convertToType(data['transfered'], [CashCount]);
    }
    return obj;
  }
}

/**
 * Details of what has been deposited during the transaction
 * @member {Array.<module:model/CashCount>} deposited
 */
TransactionCountings.prototype.deposited = undefined;

/**
 * Details of what has been dispensed during the transaction
 * @member {Array.<module:model/CashCount>} dispensed
 */
TransactionCountings.prototype.dispensed = undefined;

/**
 * Details of what has been transfered during the transaction
 * @member {Array.<module:model/CashCount>} transfered
 */
TransactionCountings.prototype.transfered = undefined;

