/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class TransactionTypeEnum.
 * @enum {String}
 * @readonly
 */
const TransactionTypeEnum = {
  /**
   * value: "bagCollection"
   * @const
   */
  bagCollection: "bagCollection",

  /**
   * value: "cassetteCollection"
   * @const
   */
  cassetteCollection: "cassetteCollection",

  /**
   * value: "emptyOut"
   * @const
   */
  emptyOut: "emptyOut",

  /**
   * value: "manualRefill"
   * @const
   */
  manualRefill: "manualRefill",

  /**
   * value: "payment"
   * @const
   */
  payment: "payment",

  /**
   * value: "refill"
   * @const
   */
  refill: "refill",

  /**
   * value: "transfer"
   * @const
   */
  transfer: "transfer",

  /**
   * value: "withdrawal"
   * @const
   */
  withdrawal: "withdrawal",

  /**
   * value: "changedContent"
   * @const
   */
  changedContent: "changedContent",

  /**
   * value: "none"
   * @const
   */
  none: "none",

  /**
   * Returns a <code>TransactionTypeEnum</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/TransactionTypeEnum} The enum <code>TransactionTypeEnum</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {TransactionTypeEnum};