/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TransferSource model module.
 * @module model/TransferSource
 * @version v1
 */
export class TransferSource {
  /**
   * Constructs a new <code>TransferSource</code>.
   * @alias module:model/TransferSource
   * @class
   * @param stockIndex {Number} Source stock index
   * @param quantity {Number} Quantity to transfer
   */
  constructor(stockIndex, quantity) {
    this.stockIndex = stockIndex;
    this.quantity = quantity;
  }

  /**
   * Constructs a <code>TransferSource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TransferSource} obj Optional instance to populate.
   * @return {module:model/TransferSource} The populated <code>TransferSource</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TransferSource();
      if (data.hasOwnProperty('stockIndex'))
        obj.stockIndex = ApiClient.convertToType(data['stockIndex'], 'Number');
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ApiClient.convertToType(data['quantity'], 'Number');
    }
    return obj;
  }
}

/**
 * Source stock index
 * @member {Number} stockIndex
 */
TransferSource.prototype.stockIndex = undefined;

/**
 * Quantity to transfer
 * @member {Number} quantity
 */
TransferSource.prototype.quantity = undefined;

