/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class TrayStatusEnum.
 * @enum {String}
 * @readonly
 */
const TrayStatusEnum = {
  /**
   * value: "unknown"
   * @const
   */
  unknown: "unknown",

  /**
   * value: "empty"
   * @const
   */
  empty: "empty",

  /**
   * value: "full"
   * @const
   */
  full: "full",

  /**
   * Returns a <code>TrayStatusEnum</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/TrayStatusEnum} The enum <code>TrayStatusEnum</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {TrayStatusEnum};