/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {CommandFailedResponse} from '../model/CommandFailedResponse';
import {EmptyOutOperationStatus} from '../model/EmptyOutOperationStatus';
import {ProblemDetails} from '../model/ProblemDetails';
import {StartEmptyOutReqData} from '../model/StartEmptyOutReqData';
import {StartOperationResponse} from '../model/StartOperationResponse';

/**
* EmptyOut service.
* @module api/EmptyOutApi
* @version v1
*/
export class EmptyOutApi {

    /**
    * Constructs a new EmptyOutApi. 
    * @alias module:api/EmptyOutApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the apiV1OperationEmptyOutStartPost operation.
     * @callback moduleapi/EmptyOutApi~apiV1OperationEmptyOutStartPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/StartOperationResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Start a new empty out operation to empty some/all stocks
     * Request to start a new empty out operation, to empty completely the stocks whose indexes have been passed as parameter.  Obviously, it is possible only with the stocks having type drum or hopper.
     * @param {module:model/StartEmptyOutReqData} body Object containing the stock index array to be emptied
     * @param {Object} opts Optional parameters
     * @param {String} opts.transactionRef Optional text to be linked to the transaction (for example it could be the transaction identifier in the client application or the POS transaction identifier or the ticket identifier)
     * @param {module:api/EmptyOutApi~apiV1OperationEmptyOutStartPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiV1OperationEmptyOutStartPost(body, opts, callback) {
      opts = opts || {};
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling apiV1OperationEmptyOutStartPost");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'transactionRef': opts['transactionRef']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = ['application/json', 'text/json', 'application/_*+json'];
      let accepts = ['application/json'];
      let returnType = StartOperationResponse;

      return this.apiClient.callApi(
        '/api/v1/operation/EmptyOut/start', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiV1OperationEmptyOutStatusGet operation.
     * @callback moduleapi/EmptyOutApi~apiV1OperationEmptyOutStatusGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/EmptyOutOperationStatus{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve the status of the empty out operation
     * Request to retrieve the status of the empty out operation, once the empty out is started - minimum time between 2 requests 300ms
     * @param {module:api/EmptyOutApi~apiV1OperationEmptyOutStatusGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiV1OperationEmptyOutStatusGet(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = EmptyOutOperationStatus;

      return this.apiClient.callApi(
        '/api/v1/operation/EmptyOut/status', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}