/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {CommandFailedResponse} from '../model/CommandFailedResponse';
import {OperationStatus} from '../model/OperationStatus';
import {ProblemDetails} from '../model/ProblemDetails';

/**
* Reset service.
* @module api/ResetApi
* @version v1
*/
export class ResetApi {

    /**
    * Constructs a new ResetApi. 
    * @alias module:api/ResetApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the apiV1OperationResetStartPost operation.
     * @callback moduleapi/ResetApi~apiV1OperationResetStartPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Start a new device reset operation
     * Request to start a new device reset operation
     * @param {module:api/ResetApi~apiV1OperationResetStartPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    apiV1OperationResetStartPost(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/v1/operation/Reset/start', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiV1OperationResetStatusGet operation.
     * @callback moduleapi/ResetApi~apiV1OperationResetStatusGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/OperationStatus{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve the status of the reset operation
     * Request to retrieve the status of the reset operation, once the reset is started - minimum time between 2 requests 300ms
     * @param {module:api/ResetApi~apiV1OperationResetStatusGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiV1OperationResetStatusGet(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = OperationStatus;

      return this.apiClient.callApi(
        '/api/v1/operation/Reset/status', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}