/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {CashDetail} from '../model/CashDetail';
import {CommandFailedResponse} from '../model/CommandFailedResponse';
import {CurrencyAmount} from '../model/CurrencyAmount';
import {ProblemDetails} from '../model/ProblemDetails';
import {StartOperationResponse} from '../model/StartOperationResponse';
import {WithdrawalOperationStatus} from '../model/WithdrawalOperationStatus';

/**
* Withdrawal service.
* @module api/WithdrawalApi
* @version v1
*/
export class WithdrawalApi {

    /**
    * Constructs a new WithdrawalApi. 
    * @alias module:api/WithdrawalApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the apiV1OperationWithdrawalStartByCurrencyAmountPost operation.
     * @callback moduleapi/WithdrawalApi~apiV1OperationWithdrawalStartByCurrencyAmountPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/StartOperationResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Start new withdrawal operation by currency amount
     * Request to start a new withdrawal operation.  This functionality allows to withdrawal cash from the machine, specifying the currency and the amount to withdraw
     * @param {Object} opts Optional parameters
     * @param {module:model/CurrencyAmount} opts.body Object containing the currency and the amount to withdraw
     * @param {String} opts.transactionRef Optional text to be linked to the transaction (for example it could be the transaction identifier in the client application or the POS transaction identifier or the ticket identifier)
     * @param {module:api/WithdrawalApi~apiV1OperationWithdrawalStartByCurrencyAmountPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiV1OperationWithdrawalStartByCurrencyAmountPost(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        
      };
      let queryParams = {
        'transactionRef': opts['transactionRef']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = ['application/json', 'text/json', 'application/_*+json'];
      let accepts = ['application/json'];
      let returnType = StartOperationResponse;

      return this.apiClient.callApi(
        '/api/v1/operation/Withdrawal/startByCurrencyAmount', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiV1OperationWithdrawalStartByDenominationPost operation.
     * @callback moduleapi/WithdrawalApi~apiV1OperationWithdrawalStartByDenominationPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/StartOperationResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Start new withdrawal operation by denomination
     * Request to start a new withdrawal operation.  This functionality allows to withdrawal cash from the machine, specifying the list of denominations and their quantities
     * @param {Object} opts Optional parameters
     * @param {Array.<module:model/CashDetail>} opts.body Object containing the list of cash detail to withdraw, quantities and denominations
     * @param {String} opts.transactionRef Optional text to be linked to the transaction (for example it could be the transaction identifier in the client application or the POS transaction identifier or the ticket identifier)
     * @param {module:api/WithdrawalApi~apiV1OperationWithdrawalStartByDenominationPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiV1OperationWithdrawalStartByDenominationPost(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        
      };
      let queryParams = {
        'transactionRef': opts['transactionRef']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = ['application/json', 'text/json', 'application/_*+json'];
      let accepts = ['application/json'];
      let returnType = StartOperationResponse;

      return this.apiClient.callApi(
        '/api/v1/operation/Withdrawal/startByDenomination', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiV1OperationWithdrawalStatusGet operation.
     * @callback moduleapi/WithdrawalApi~apiV1OperationWithdrawalStatusGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/WithdrawalOperationStatus{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve the status of the transfer operation
     * Request to retrieve the status of the transfer operation, once the transfer is started - minimum time between 2 requests 300ms
     * @param {module:api/WithdrawalApi~apiV1OperationWithdrawalStatusGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiV1OperationWithdrawalStatusGet(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = WithdrawalOperationStatus;

      return this.apiClient.callApi(
        '/api/v1/operation/Withdrawal/status', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}