/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InLaneApi);
  }
}(this, function(expect, InLaneApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('BanknoteBagTypeEnum', function() {
      beforeEach(function() {
        instance = InLaneApi.BanknoteBagTypeEnum;
      });

      it('should create an instance of BanknoteBagTypeEnum', function() {
        // TODO: update the code to test BanknoteBagTypeEnum
        expect(instance).to.be.a('object');
      });

      it('should have the property none', function() {
        expect(instance).to.have.property('none');
        expect(instance.none).to.be("none");
      });

      it('should have the property selfSealing', function() {
        expect(instance).to.have.property('selfSealing');
        expect(instance.selfSealing).to.be("selfSealing");
      });

      it('should have the property canvas', function() {
        expect(instance).to.have.property('canvas');
        expect(instance.canvas).to.be("canvas");
      });

      it('should have the property heatSealing', function() {
        expect(instance).to.have.property('heatSealing');
        expect(instance.heatSealing).to.be("heatSealing");
      });

      it('should have the property stacking', function() {
        expect(instance).to.have.property('stacking');
        expect(instance.stacking).to.be("stacking");
      });

      it('should have the property heatSealingV2', function() {
        expect(instance).to.have.property('heatSealingV2');
        expect(instance.heatSealingV2).to.be("heatSealingV2");
      });

      it('should have the property smartCanvas', function() {
        expect(instance).to.have.property('smartCanvas');
        expect(instance.smartCanvas).to.be("smartCanvas");
      });

      it('should have the property unknown', function() {
        expect(instance).to.have.property('unknown');
        expect(instance.unknown).to.be("unknown");
      });

    });
  });

}));
