/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InLaneApi);
  }
}(this, function(expect, InLaneApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DepositStatus', function() {
      beforeEach(function() {
        instance = InLaneApi.DepositStatus;
      });

      it('should create an instance of DepositStatus', function() {
        // TODO: update the code to test DepositStatus
        expect(instance).to.be.a('object');
      });

      it('should have the property running', function() {
        expect(instance).to.have.property('running');
        expect(instance.running).to.be("running");
      });

      it('should have the property jammed', function() {
        expect(instance).to.have.property('jammed');
        expect(instance.jammed).to.be("jammed");
      });

      it('should have the property done', function() {
        expect(instance).to.have.property('done');
        expect(instance.done).to.be("done");
      });

      it('should have the property depositNotesIn', function() {
        expect(instance).to.have.property('depositNotesIn');
        expect(instance.depositNotesIn).to.be("depositNotesIn");
      });

      it('should have the property removeNotesOut', function() {
        expect(instance).to.have.property('removeNotesOut');
        expect(instance.removeNotesOut).to.be("removeNotesOut");
      });

    });
  });

}));
