/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InLaneApi);
  }
}(this, function(expect, InLaneApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DeviceContentDetail', function() {
      beforeEach(function() {
        instance = new InLaneApi.DeviceContentDetail();
      });

      it('should create an instance of DeviceContentDetail', function() {
        // TODO: update the code to test DeviceContentDetail
        expect(instance).to.be.a(InLaneApi.DeviceContentDetail);
      });

      it('should have the property content (base name: "content")', function() {
        // TODO: update the code to test the property content
        expect(instance).to.have.property('content');
        // expect(instance.content).to.be(expectedValueLiteral);
      });

      it('should have the property stockIndex (base name: "stockIndex")', function() {
        // TODO: update the code to test the property stockIndex
        expect(instance).to.have.property('stockIndex');
        // expect(instance.stockIndex).to.be(expectedValueLiteral);
      });

    });
  });

}));
