/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InLaneApi);
  }
}(this, function(expect, InLaneApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DeviceInfo', function() {
      beforeEach(function() {
        instance = new InLaneApi.DeviceInfo();
      });

      it('should create an instance of DeviceInfo', function() {
        // TODO: update the code to test DeviceInfo
        expect(instance).to.be.a(InLaneApi.DeviceInfo);
      });

      it('should have the property model (base name: "model")', function() {
        // TODO: update the code to test the property model
        expect(instance).to.have.property('model');
        // expect(instance.model).to.be(expectedValueLiteral);
      });

      it('should have the property serialNumber (base name: "serialNumber")', function() {
        // TODO: update the code to test the property serialNumber
        expect(instance).to.have.property('serialNumber');
        // expect(instance.serialNumber).to.be(expectedValueLiteral);
      });

      it('should have the property banknotesModule (base name: "banknotesModule")', function() {
        // TODO: update the code to test the property banknotesModule
        expect(instance).to.have.property('banknotesModule');
        // expect(instance.banknotesModule).to.be(expectedValueLiteral);
      });

      it('should have the property coinsModule (base name: "coinsModule")', function() {
        // TODO: update the code to test the property coinsModule
        expect(instance).to.have.property('coinsModule');
        // expect(instance.coinsModule).to.be(expectedValueLiteral);
      });

      it('should have the property safeDoor (base name: "safeDoor")', function() {
        // TODO: update the code to test the property safeDoor
        expect(instance).to.have.property('safeDoor');
        // expect(instance.safeDoor).to.be(expectedValueLiteral);
      });

    });
  });

}));
