/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InLaneApi);
  }
}(this, function(expect, InLaneApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DeviceInfoResponse', function() {
      beforeEach(function() {
        instance = new InLaneApi.DeviceInfoResponse();
      });

      it('should create an instance of DeviceInfoResponse', function() {
        // TODO: update the code to test DeviceInfoResponse
        expect(instance).to.be.a(InLaneApi.DeviceInfoResponse);
      });

      it('should have the property api (base name: "api")', function() {
        // TODO: update the code to test the property api
        expect(instance).to.have.property('api');
        // expect(instance.api).to.be(expectedValueLiteral);
      });

      it('should have the property device (base name: "device")', function() {
        // TODO: update the code to test the property device
        expect(instance).to.have.property('device');
        // expect(instance.device).to.be(expectedValueLiteral);
      });

    });
  });

}));
