/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InLaneApi);
  }
}(this, function(expect, InLaneApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DoorTypeEnum', function() {
      beforeEach(function() {
        instance = InLaneApi.DoorTypeEnum;
      });

      it('should create an instance of DoorTypeEnum', function() {
        // TODO: update the code to test DoorTypeEnum
        expect(instance).to.be.a('object');
      });

      it('should have the property unique', function() {
        expect(instance).to.have.property('unique');
        expect(instance.unique).to.be("unique");
      });

      it('should have the property banknotesModule', function() {
        expect(instance).to.have.property('banknotesModule');
        expect(instance.banknotesModule).to.be("banknotesModule");
      });

      it('should have the property coinsModule', function() {
        expect(instance).to.have.property('coinsModule');
        expect(instance.coinsModule).to.be("coinsModule");
      });

    });
  });

}));
