/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InLaneApi);
  }
}(this, function(expect, InLaneApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ModuleStatus', function() {
      beforeEach(function() {
        instance = new InLaneApi.ModuleStatus();
      });

      it('should create an instance of ModuleStatus', function() {
        // TODO: update the code to test ModuleStatus
        expect(instance).to.be.a(InLaneApi.ModuleStatus);
      });

      it('should have the property errorArea (base name: "errorArea")', function() {
        // TODO: update the code to test the property errorArea
        expect(instance).to.have.property('errorArea');
        // expect(instance.errorArea).to.be(expectedValueLiteral);
      });

      it('should have the property deviceErrorCode (base name: "deviceErrorCode")', function() {
        // TODO: update the code to test the property deviceErrorCode
        expect(instance).to.have.property('deviceErrorCode');
        // expect(instance.deviceErrorCode).to.be(expectedValueLiteral);
      });

      it('should have the property coverOpened (base name: "coverOpened")', function() {
        // TODO: update the code to test the property coverOpened
        expect(instance).to.have.property('coverOpened');
        // expect(instance.coverOpened).to.be(expectedValueLiteral);
      });

      it('should have the property cleaningNecessary (base name: "cleaningNecessary")', function() {
        // TODO: update the code to test the property cleaningNecessary
        expect(instance).to.have.property('cleaningNecessary');
        // expect(instance.cleaningNecessary).to.be(expectedValueLiteral);
      });

      it('should have the property inTrayStatus (base name: "inTrayStatus")', function() {
        // TODO: update the code to test the property inTrayStatus
        expect(instance).to.have.property('inTrayStatus');
        // expect(instance.inTrayStatus).to.be(expectedValueLiteral);
      });

      it('should have the property outTrayStatus (base name: "outTrayStatus")', function() {
        // TODO: update the code to test the property outTrayStatus
        expect(instance).to.have.property('outTrayStatus');
        // expect(instance.outTrayStatus).to.be(expectedValueLiteral);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

    });
  });

}));
