/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InLaneApi);
  }
}(this, function(expect, InLaneApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PaymentOperationStatus', function() {
      beforeEach(function() {
        instance = new InLaneApi.PaymentOperationStatus();
      });

      it('should create an instance of PaymentOperationStatus', function() {
        // TODO: update the code to test PaymentOperationStatus
        expect(instance).to.be.a(InLaneApi.PaymentOperationStatus);
      });

      it('should have the property paymentStatus (base name: "paymentStatus")', function() {
        // TODO: update the code to test the property paymentStatus
        expect(instance).to.have.property('paymentStatus');
        // expect(instance.paymentStatus).to.be(expectedValueLiteral);
      });

      it('should have the property depositCounting (base name: "depositCounting")', function() {
        // TODO: update the code to test the property depositCounting
        expect(instance).to.have.property('depositCounting');
        // expect(instance.depositCounting).to.be(expectedValueLiteral);
      });

      it('should have the property depositTotal (base name: "depositTotal")', function() {
        // TODO: update the code to test the property depositTotal
        expect(instance).to.have.property('depositTotal');
        // expect(instance.depositTotal).to.be(expectedValueLiteral);
      });

      it('should have the property dispenseCounting (base name: "dispenseCounting")', function() {
        // TODO: update the code to test the property dispenseCounting
        expect(instance).to.have.property('dispenseCounting');
        // expect(instance.dispenseCounting).to.be(expectedValueLiteral);
      });

      it('should have the property dispenseTotal (base name: "dispenseTotal")', function() {
        // TODO: update the code to test the property dispenseTotal
        expect(instance).to.have.property('dispenseTotal');
        // expect(instance.dispenseTotal).to.be(expectedValueLiteral);
      });

      it('should have the property missingAmount (base name: "missingAmount")', function() {
        // TODO: update the code to test the property missingAmount
        expect(instance).to.have.property('missingAmount');
        // expect(instance.missingAmount).to.be(expectedValueLiteral);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

      it('should have the property errorDescription (base name: "errorDescription")', function() {
        // TODO: update the code to test the property errorDescription
        expect(instance).to.have.property('errorDescription');
        // expect(instance.errorDescription).to.be(expectedValueLiteral);
      });

    });
  });

}));
