/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InLaneApi);
  }
}(this, function(expect, InLaneApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('StartTransferReqData', function() {
      beforeEach(function() {
        instance = new InLaneApi.StartTransferReqData();
      });

      it('should create an instance of StartTransferReqData', function() {
        // TODO: update the code to test StartTransferReqData
        expect(instance).to.be.a(InLaneApi.StartTransferReqData);
      });

      it('should have the property sources (base name: "sources")', function() {
        // TODO: update the code to test the property sources
        expect(instance).to.have.property('sources');
        // expect(instance.sources).to.be(expectedValueLiteral);
      });

      it('should have the property destinationIndex (base name: "destinationIndex")', function() {
        // TODO: update the code to test the property destinationIndex
        expect(instance).to.have.property('destinationIndex');
        // expect(instance.destinationIndex).to.be(expectedValueLiteral);
      });

    });
  });

}));
