/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InLaneApi);
  }
}(this, function(expect, InLaneApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('StockTypeEnum', function() {
      beforeEach(function() {
        instance = InLaneApi.StockTypeEnum;
      });

      it('should create an instance of StockTypeEnum', function() {
        // TODO: update the code to test StockTypeEnum
        expect(instance).to.be.a('object');
      });

      it('should have the property drum', function() {
        expect(instance).to.have.property('drum');
        expect(instance.drum).to.be("drum");
      });

      it('should have the property bag', function() {
        expect(instance).to.have.property('bag');
        expect(instance.bag).to.be("bag");
      });

      it('should have the property hopper', function() {
        expect(instance).to.have.property('hopper');
        expect(instance.hopper).to.be("hopper");
      });

      it('should have the property cassette', function() {
        expect(instance).to.have.property('cassette');
        expect(instance.cassette).to.be("cassette");
      });

      it('should have the property unknown', function() {
        expect(instance).to.have.property('unknown');
        expect(instance.unknown).to.be("unknown");
      });

    });
  });

}));
