/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InLaneApi);
  }
}(this, function(expect, InLaneApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('StockStatus', function() {
      beforeEach(function() {
        instance = new InLaneApi.StockStatus();
      });

      it('should create an instance of StockStatus', function() {
        // TODO: update the code to test StockStatus
        expect(instance).to.be.a(InLaneApi.StockStatus);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

      it('should have the property stockType (base name: "stockType")', function() {
        // TODO: update the code to test the property stockType
        expect(instance).to.have.property('stockType');
        // expect(instance.stockType).to.be(expectedValueLiteral);
      });

      it('should have the property cashMediaType (base name: "cashMediaType")', function() {
        // TODO: update the code to test the property cashMediaType
        expect(instance).to.have.property('cashMediaType');
        // expect(instance.cashMediaType).to.be(expectedValueLiteral);
      });

    });
  });

}));
