/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InLaneApi);
  }
}(this, function(expect, InLaneApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('TransactionResponse', function() {
      beforeEach(function() {
        instance = new InLaneApi.TransactionResponse();
      });

      it('should create an instance of TransactionResponse', function() {
        // TODO: update the code to test TransactionResponse
        expect(instance).to.be.a(InLaneApi.TransactionResponse);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property timestamp (base name: "timestamp")', function() {
        // TODO: update the code to test the property timestamp
        expect(instance).to.have.property('timestamp');
        // expect(instance.timestamp).to.be(expectedValueLiteral);
      });

      it('should have the property username (base name: "username")', function() {
        // TODO: update the code to test the property username
        expect(instance).to.have.property('username');
        // expect(instance.username).to.be(expectedValueLiteral);
      });

      it('should have the property type (base name: "type")', function() {
        // TODO: update the code to test the property type
        expect(instance).to.have.property('type');
        // expect(instance.type).to.be(expectedValueLiteral);
      });

      it('should have the property countings (base name: "countings")', function() {
        // TODO: update the code to test the property countings
        expect(instance).to.have.property('countings');
        // expect(instance.countings).to.be(expectedValueLiteral);
      });

      it('should have the property totals (base name: "totals")', function() {
        // TODO: update the code to test the property totals
        expect(instance).to.have.property('totals');
        // expect(instance.totals).to.be(expectedValueLiteral);
      });

      it('should have the property transactionReference (base name: "transactionReference")', function() {
        // TODO: update the code to test the property transactionReference
        expect(instance).to.have.property('transactionReference');
        // expect(instance.transactionReference).to.be(expectedValueLiteral);
      });

    });
  });

}));
