/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InLaneApi);
  }
}(this, function(expect, InLaneApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('TransactionCountings', function() {
      beforeEach(function() {
        instance = new InLaneApi.TransactionCountings();
      });

      it('should create an instance of TransactionCountings', function() {
        // TODO: update the code to test TransactionCountings
        expect(instance).to.be.a(InLaneApi.TransactionCountings);
      });

      it('should have the property deposited (base name: "deposited")', function() {
        // TODO: update the code to test the property deposited
        expect(instance).to.have.property('deposited');
        // expect(instance.deposited).to.be(expectedValueLiteral);
      });

      it('should have the property dispensed (base name: "dispensed")', function() {
        // TODO: update the code to test the property dispensed
        expect(instance).to.have.property('dispensed');
        // expect(instance.dispensed).to.be(expectedValueLiteral);
      });

      it('should have the property transfered (base name: "transfered")', function() {
        // TODO: update the code to test the property transfered
        expect(instance).to.have.property('transfered');
        // expect(instance.transfered).to.be(expectedValueLiteral);
      });

    });
  });

}));
