/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InLaneApi);
  }
}(this, function(expect, InLaneApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new InLaneApi.DeviceInfoApi();
  });

  describe('(package)', function() {
    describe('DeviceInfoApi', function() {
      describe('apiV1DeviceInfoConfigurationGet', function() {
        it('should call apiV1DeviceInfoConfigurationGet successfully', function(done) {
          // TODO: uncomment apiV1DeviceInfoConfigurationGet call and complete the assertions
          /*

          instance.apiV1DeviceInfoConfigurationGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(InLaneApi.StockConfiguration);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiV1DeviceInfoCurrencyExchangeRatesGet', function() {
        it('should call apiV1DeviceInfoCurrencyExchangeRatesGet successfully', function(done) {
          // TODO: uncomment apiV1DeviceInfoCurrencyExchangeRatesGet call and complete the assertions
          /*

          instance.apiV1DeviceInfoCurrencyExchangeRatesGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(InLaneApi.ExchangeRate);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiV1DeviceInfoCurrencyExchangeRatesPost', function() {
        it('should call apiV1DeviceInfoCurrencyExchangeRatesPost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiV1DeviceInfoCurrencyExchangeRatesPost call
          /*

          instance.apiV1DeviceInfoCurrencyExchangeRatesPost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiV1DeviceInfoGet', function() {
        it('should call apiV1DeviceInfoGet successfully', function(done) {
          // TODO: uncomment apiV1DeviceInfoGet call and complete the assertions
          /*

          instance.apiV1DeviceInfoGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(InLaneApi.DeviceInfoResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiV1DeviceInfoMainCurrencyGet', function() {
        it('should call apiV1DeviceInfoMainCurrencyGet successfully', function(done) {
          // TODO: uncomment apiV1DeviceInfoMainCurrencyGet call and complete the assertions
          /*

          instance.apiV1DeviceInfoMainCurrencyGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(InLaneApi.CurrencyString);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
