/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InLaneApi);
  }
}(this, function(expect, InLaneApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new InLaneApi.RefillApi();
  });

  describe('(package)', function() {
    describe('RefillApi', function() {
      describe('apiV1OperationRefillEndPost', function() {
        it('should call apiV1OperationRefillEndPost successfully', function(done) {
          // TODO: uncomment apiV1OperationRefillEndPost call
          /*

          instance.apiV1OperationRefillEndPost(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiV1OperationRefillStartPost', function() {
        it('should call apiV1OperationRefillStartPost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiV1OperationRefillStartPost call and complete the assertions
          /*
          var opts = {};

          instance.apiV1OperationRefillStartPost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(InLaneApi.StartOperationResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiV1OperationRefillStatusGet', function() {
        it('should call apiV1OperationRefillStatusGet successfully', function(done) {
          // TODO: uncomment apiV1OperationRefillStatusGet call and complete the assertions
          /*

          instance.apiV1OperationRefillStatusGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(InLaneApi.RefillOperationStatus);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
