/*
 * InLane API
 * InLane communication Web Api
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InLaneApi);
  }
}(this, function(expect, InLaneApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new InLaneApi.TransferAllButKitApi();
  });

  describe('(package)', function() {
    describe('TransferAllButKitApi', function() {
      describe('apiV1OperationTransferAllButKitCheckUnderThresholdKitDenominationsGet', function() {
        it('should call apiV1OperationTransferAllButKitCheckUnderThresholdKitDenominationsGet successfully', function(done) {
          // TODO: uncomment apiV1OperationTransferAllButKitCheckUnderThresholdKitDenominationsGet call and complete the assertions
          /*

          instance.apiV1OperationTransferAllButKitCheckUnderThresholdKitDenominationsGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(InLaneApi.KitDenomination);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiV1OperationTransferAllButKitConfigurationGet', function() {
        it('should call apiV1OperationTransferAllButKitConfigurationGet successfully', function(done) {
          // TODO: uncomment apiV1OperationTransferAllButKitConfigurationGet call and complete the assertions
          /*

          instance.apiV1OperationTransferAllButKitConfigurationGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(InLaneApi.MinimumKitConfiguration);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiV1OperationTransferAllButKitConfigurationPost', function() {
        it('should call apiV1OperationTransferAllButKitConfigurationPost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiV1OperationTransferAllButKitConfigurationPost call
          /*
          var opts = {};

          instance.apiV1OperationTransferAllButKitConfigurationPost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiV1OperationTransferAllButKitStartPost', function() {
        it('should call apiV1OperationTransferAllButKitStartPost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiV1OperationTransferAllButKitStartPost call and complete the assertions
          /*
          var opts = {};

          instance.apiV1OperationTransferAllButKitStartPost(body, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(InLaneApi.StartOperationResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiV1OperationTransferAllButKitStatusGet', function() {
        it('should call apiV1OperationTransferAllButKitStatusGet successfully', function(done) {
          // TODO: uncomment apiV1OperationTransferAllButKitStatusGet call and complete the assertions
          /*

          instance.apiV1OperationTransferAllButKitStatusGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(InLaneApi.TransferAllButKitOperationStatus);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
